---

- name: "[NGINX] :: create public_html directory"
  file:
    path: "{{ data_mount_root }}/{{ www_directory }}"
    state: directory
    mode: 0755
    owner: "{{ media_user_uid }}"
    group: "{{ media_user_gid }}"
  notify:
    - restart nginx

- name: "[NGINX] :: Install SSL Key"
  copy:
    content: "{{ item.sslkeycontent }}"
    dest: "{{ item.sslkeyfile }}"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ nginx_vhosts_ssl }}"
  notify:
    - restart nginx

- name: "[NGINX] :: Install SSL Certificate Chain"
  copy:
    content: "{{ item.sslcertcontent }}"
    dest: "{{ item.sslcertfile }}"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ nginx_vhosts_ssl }}"
  notify:
    - restart nginx

- name: "[NGINX] :: Remove default vhost configs"
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ nginx_default_site }}"
  notify:
    - restart nginx

- name: "[NGINX] :: Build nginx.conf template"
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: "[NGINX] :: Build proxy.conf template"
  template:
    src: proxy.conf.j2
    dest: /etc/nginx/proxy.conf
  notify:
    - restart nginx

- name: "[NGINX] :: Build ssl.conf template"
  template:
    src: ssl.conf.j2
    dest: /etc/nginx/ssl.conf
  notify:
    - restart nginx

- name: "[NGINX] :: Build NGINX vhost template"
  template:
    src: default.conf.j2
    dest: "{{ nginx_cfg_dir }}/{{ www_domain }}"
  notify:
    - restart nginx

- name: "[NGINX] :: Build NGINX SSL vhost template"
  template:
    src: default-ssl.conf.j2
    dest: "{{ nginx_cfg_dir }}/{{ www_domain }}-ssl"
  notify:
    - restart nginx

- name: "[NGINX] :: restart nginx"
  service:
    name: nginx
    state: restarted
