---

- name: "[NGINX] :: create public_html directory"
  file:
    path: "{{ nginx_default_docroot }}"
    state: directory
    mode: 0755
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
  notify:
    - restart nginx

- name: "[NGINX] :: Install SSL Key"
  copy:
    content: "{{ item.ssl_privkey }}"
    dest: "{{ item.ssl_keypath }}"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ nginx_vhosts_ssl }}"
  notify:
    - restart nginx

- name: "[NGINX] :: Install SSL Certificate Chain"
  copy:
    content: "{{ item.ssl_certchain }}"
    dest: "{{ item.ssl_certpath }}"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ nginx_vhosts_ssl }}"
  notify:
    - restart nginx

- name: "[NGINX] :: Remove default vhost configs"
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ nginx_default_site }}"
  notify:
    - restart nginx

- name: "[NGINX] :: Build nginx.conf template"
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: "[NGINX] :: Build proxy.conf template"
  template:
    src: proxy.conf.j2
    dest: /etc/nginx/proxy.conf
  notify:
    - restart nginx

- name: "[NGINX] :: Build ssl.conf template"
  template:
    src: ssl.conf.j2
    dest: /etc/nginx/ssl.conf
  notify:
    - restart nginx

- name: "[NGINX] :: Build NGINX vhost template"
  template:
    src: default.conf.j2
    dest: "{{ nginx_cfg_dir }}/{{ www_domain }}"
  notify:
    - restart nginx

- name: "[NGINX] :: Build NGINX SSL vhost template"
  template:
    src: default-ssl.conf.j2
    dest: "{{ nginx_cfg_dir }}/{{ www_domain }}-ssl"
  notify:
    - restart nginx

#- name: "[NGINX] :: Copy PHP-FPM php.ini"
#  template:
#    src: php.ini.j2
#    dest: "/etc/php/{{ php_version }}/fpm/php.ini"
#  register: update_fpm_ini
#
#- name: "[NGINX] :: Copy PHP-FPM www.conf"
#  template:
#    src: www.conf.j2
#    dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
#  register: update_fpm_www
#
#- name: "[NGINX] :: Restart php-fpm"
#  service:
#    name: "php{{ php_version }}-fpm"
#    state: restarted
#  when: update_fpm_www is changed or update_fpm_ini is changed

- name: "[FAIL2BAN] :: Copy Fail2Ban SSH Private Key"
  copy:
    mode: 0600
    owner: root
    content: "{{ fail2ban_ssh_private_key }}"
    dest: /root/.ssh/id_rsa
  when: fail2ban_ssh_private_key is defined and fail2ban_ssh_private_key != None

- name: "[FAIL2BAN] :: Copy Fail2Ban Filters"
  copy:
    src: "fail2ban/filter.d/"
    dest: "/etc/fail2ban/filter.d/"
  notify: restart fail2ban

- name: "[FAIL2BAN] :: Copy Fail2Ban Local Config"
  template:
    src: "fail2ban/fail2ban.local.j2"
    dest: "/etc/fail2ban/fail2ban.local"
  notify: restart fail2ban

- name: "[FAIL2BAN] :: Copy Fail2Ban Jail Local Config"
  template:
    src: "fail2ban/jail.local.j2"
    dest: "/etc/fail2ban/jail.local"
  notify: restart fail2ban

- name: "[FAIL2BAN] :: Copy Fail2Ban URLTable Action"
  template:
    src: "fail2ban/urltable_action.j2"
    dest: "/etc/fail2ban/action.d/urltable.conf"
  notify: restart fail2ban