---
- name: "[FAIL2BAN] :: Copy Fail2Ban SSH Private Key"
  copy:
    mode: 0600
    owner: root
    content: "{{ fail2ban_ssh_private_key }}"
    dest: /root/.ssh/id_rsa
  when: fail2ban_ssh_private_key is defined and fail2ban_ssh_private_key != None

- name: "[FAIL2BAN] :: Copy Fail2Ban Filters"
  copy:
    src: "fail2ban/filter.d/"
    dest: "/etc/fail2ban/filter.d/"
  register: fail2ban_filter_update

- name: "[FAIL2BAN] :: Copy Fail2Ban Local Config"
  template:
    src: "fail2ban/fail2ban.local.j2"
    dest: "/etc/fail2ban/fail2ban.local"
  register: fail2ban_local_update

- name: "[FAIL2BAN] :: Copy Fail2Ban Jail Local Config"
  template:
    src: "fail2ban/jail.local.j2"
    dest: "/etc/fail2ban/jail.local"
  register: fail2ban_jail_update

- name: "[FAIL2BAN] :: Copy Fail2Ban URLTable Action"
  template:
    src: "fail2ban/urltable_action.j2"
    dest: "/etc/fail2ban/action.d/urltable.conf"
  register: fail2ban_action_update

- name: Restart the fail2ban service
  systemd:
    name: fail2ban
    state: restarted
    enabled: yes
  when: fail2ban_action_update.changed or
        fail2ban_jail_update.changed or
        fail2ban_local_update.changed or
        fail2ban_filter_update.changed
