---

- name: create public_html directory
  file:
    path: "{{ data_mount_root }}/{{ www_directory }}"
    state: directory
    mode: 0755
    owner: "{{ media_user_uid }}"
    group: "{{ media_user_gid }}"
  notify:
    - restart nginx

- name: Install SSL Key
  copy:
    content: "{{ item.sslkeycontent }}"
    dest: "{{ item.sslkeyfile }}"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ nginx_vhosts_ssl }}"
  notify:
    - restart nginx

- name: Install SSL Certificate Chain
  copy:
    content: "{{ item.sslcertcontent }}"
    dest: "{{ item.sslcertfile }}"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ nginx_vhosts_ssl }}"
  notify:
    - restart nginx

- name: remove nginx default.conf
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ nginx_default_site }}"
  notify:
    - restart nginx

- name: template nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: template nginx vhost configs
  template:
    src: default.conf.j2
    dest: "/etc/nginx/sites-available/{{ www_domain }}"
  notify:
    - restart nginx

- name: enable default site
  file:
    state: link
    src: "/etc/nginx/sites-available/{{ www_domain }}"
    dest: "/etc/nginx/sites-enabled/{{ www_domain }}"
    owner: "{{ media_user_uid }}"
    group: "{{ media_user_gid }}"

- name: restart nginx
  service:
    name: nginx
    state: restarted
