- name: Configure rtmp transcode data directories
  block:
    - name: "create camera feed transcode directory"
      file:
        state: directory
        owner: "{{ nginx_user }}"
        group: "{{ nginx_group }}"
        dest: "{{ nginx_hls_camera_feed_transcode_dir }}"

    - name: "create camera feed index file"
      file:
        state: touch
        owner: root
        group: root
        dest: "{{ nginx_hls_camera_transcode_path }}"

- name: Create transcode script and service
  block:
    - name: "create ffmpeg transcode script"
      template:
        src: rtsp_to_rtmp_transcode.sh.j2
        dest: /usr/local/bin/rtsp_to_rtmp_transcode.sh
        mode: 0755
    - name: "create ffmpeg transcode service"
      template:
        src: ffmpeg_transcode.service.j2
        dest: /etc/systemd/system/ffmpeg_transcode.service
        mode: 0755
      register: ffmpeg_transcode_service
    - name: enable ffmpeg transcode service
      systemd:
        name: ffmpeg_transcode
        state: "{% if ffmpeg_transcode_service.changed %}restarted{% else %}started{% endif %}"
        enabled: yes
        daemon_reload: yes
