- name: Configure rtmp transcode data directories
  block:
    - name: Create camera feed transcode directory
      ansible.builtin.file:
        state: directory
        mode: "0755"
        owner: "{{ nginx_user | default(nginx_default_user) }}"
        group: "{{ nginx_group | default(nginx_default_group) }}"
        dest: "{{ nginx_hls_camera_feed_transcode_dir }}"

#    - name: create camera feed index file
#      file:
#        state: touch
#        owner: root
#        group: root
#        dest: "{{ nginx_hls_camera_transcode_path }}"

- name: Create transcode script and service
  block:
    - name: Create ffmpeg transcode script
      ansible.builtin.template:
        src: rtsp_to_rtmp_transcode.sh.j2
        dest: /usr/local/bin/rtsp_to_rtmp_transcode.sh
        mode: "0755"
    - name: Create ffmpeg transcode service
      ansible.builtin.template:
        src: ffmpeg_transcode.service.j2
        dest: /etc/systemd/system/ffmpeg_transcode.service
        mode: "0755"
      register: ffmpeg_transcode_service
    - name: Enable ffmpeg transcode service
      ansible.builtin.systemd:
        name: ffmpeg_transcode
        state: "{% if ffmpeg_transcode_service.changed %}restarted{% else %}started{% endif %}"
        enabled: true
        daemon_reload: true
