---
- name: "[NGINX] :: Install NGINX"
  package:
    name: "{{ nginx_pkgs }}"
    state: present
  register: nginx_installed

- name: "[NGINX] :: Start / Enable NGINX"
  service:
    name: nginx
    state: started
    enabled: true
  when: nginx_installed is changed
