---
- name: "[NGINX] :: Install NGINX"
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ nginx_pkg }}"

- name: "[NGINX] :: Start / Enable NGINX"
  service:
    name: nginx
    state: started
    enabled: true

- name: "[FAIL2BAN] :: Install Fail2Ban"
  package:
    name: fail2ban
    state: present

- name: "[FAIL2BAN] :: Start / Enable fail2ban"
  service:
    name: fail2ban
    state: started
    enabled: true