---
- name: install nginx
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ nginx_pkg }}"

- name: enable nginx service
  service:
    name: nginx
    enabled: yes

- name: install fail2ban
  package:
    name: fail2ban
    state: present

- name: enable fail2ban service
  service:
    name: fail2ban
    enabled: yes