- name: "Disable SELinux, Configure FirewallD ports to ACCEPT [RHEL/CentOS]"
  block:
    - name: Disable SELinux
      selinux:
        state: disabled
  #   - name: Configure Firewalld allowed ports
  #     firewalld:
  #       port_forward:
  #         port: "22"
  #         proto: "tcp"
  #         toport: "22"
  #       permanent: yes
  #       zone: public
  #       immediate: yes
  #       state: enabled
  #     # loop: "{{ nginx_allowed_ports }}"
  # when: ansible_os_family == "RedHat"

#- name: configure upstream nginx rpm key
#  rpm_key:
#    key: "{{ nginx_upstream_repo_key }}"
#    state: "{% if nginx_upstream_repo %}present{% else %}absent{% endif %}"
#  when: ansible_distribution == "RedHat"
#
#- name: configure upstream nginx yum repository
#  template:
#    src: nginx.repo.j2
#    dest: /etc/yum.repos.d/nginx.repo
#  when: ansible_distribution == "RedHat" and nginx_upstream_repo
#
#- name: remove upstream nginx yum repository
#  file:
#    path: /etc/yum.repos.d/nginx.repo
#    state: absent
#  when: ansible_distribution == "RedHat" and not nginx_upstream_repo

- name: Add EPEL repository [RHEL/CentOS]
  yum:
    name: epel-release
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Add GetPageSpeed repository
  yum:
    name: https://extras.getpagespeed.com/release-latest.rpm
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: "Install Nginx Packages"
  yum:
    name: "{{ nginx_pkgs }}"
    state: present

- name: Enable NGINX service
  systemd:
    name: nginx
    enabled: yes
    daemon_reload: yes
