---
- name: "[NGINX] :: Install NGINX"
  package:
    name: "{{ nginx_pkgs }}"
    state: present
  register: nginx_installed

- name: "[NGINX] :: Start / Enable NGINX"
  service:
    name: nginx
    state: started
    enabled: true
  when: nginx_installed is changed

#- name: "[NGINX] :: Capture PHP Version"
#  shell: php -v | head -n1 | sed -n 's/PHP \([0-9]\.[0-9]\).*/\1/p'
#  args:
#    executable: /bin/bash
#  register: php_capture
#
#- set_fact:
#    php_version: "{{ php_capture.stdout }}"
#
#- debug:
#    msg: "PHP Version is {{ php_version }}"
#
#- name: "[NGINX] :: Start / Enable PHP-FPM"
#  service:
#    name: "php{{ php_version }}-fpm"
#    state: started
#    enabled: true

- name: "[FAIL2BAN] :: Install Fail2Ban"
  package:
    name: fail2ban
    state: present
  register: fail2ban_installed

- name: "[FAIL2BAN] :: Start / Enable fail2ban"
  service:
    name: fail2ban
    state: started
    enabled: true
  when: fail2ban_installed is changed