---
- name: include os specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- import_tasks: installation.yml
- import_tasks: configuration.yml

- import_tasks: install_fail2ban.yml
  when: fail2ban_enable

- import_tasks: configure_fail2ban.yml
  when: fail2ban_enable
