---

- name: Add the OS specific varibles
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: Import tasks
  ansible.builtin.import_tasks: installation.yml

- name: Import tasks
  ansible.builtin.import_tasks: configuration.yml
  tags:
    - nginx-configure

- name: Import tasks
  ansible.builtin.import_tasks: install_fail2ban.yml
  when: fail2ban_enable

- name: Import tasks
  ansible.builtin.import_tasks: configure_fail2ban.yml
  when: fail2ban_enable
  tags:
    - fail2ban-configure
