- name: Slurp ssl data from remote host
  block:
    - name: slurp latest ssl key contents
      slurp:
        src: "{{ ssl_key_slurp_path }}"
      register: ssl_key_contents
      delegate_to: "{{ ssl_slurp_remote_host|default(omit) }}"
      delegate_facts: true

    - name: set encoded ssl key contents as fact for later processing
      set_fact:
        encoded_ssl_key: "{{ ssl_key_contents['content'] }}"

    - name: slurp latest ssl certificate chain contents
      slurp:
        src: "{{ ssl_cert_slurp_path }}"
      register: ssl_cert_contents
      delegate_to: "{{ ssl_slurp_remote_host|default(omit) }}"
      delegate_facts: true

    - name: set encoded ssl cert contents as fact for later processing
      set_fact:
        encoded_ssl_cert: "{{ ssl_cert_contents['content'] }}"

    - name: set decoded ssl key and cert chain as fact for future tasks
      set_fact:
        ssl_privkey: "{{ encoded_ssl_key | b64decode }}"
        ssl_certchain: "{{ encoded_ssl_cert | b64decode }}"

    - name: print decoded ssl key and certificate chain for debugging
      debug:
        msg: |
          SSL private key: {{ ssl_privkey }}
          SSL certificate chain: {{ ssl_certchain }}
        verbosity: 1
#      no_log: True

    - name: "Ensure mounted ssl directory exists"
      file:
        path: "{{ data_mount_root }}/ssl/"
        state: directory
        mode: 0640
        owner: "{{ media_user_uid }}"
        group: "{{ media_user_gid }}"

    - name: "Install SSL Key to mounted ssl directory for other applications to use"
      copy:
        content: "{{ ssl_privkey }}"
        dest: "{{ data_mount_root }}/ssl/{{ www_domain }}.key"
        owner: "{{ media_user_uid }}"
        group: "{{ media_user_gid }}"
        mode: 0600

    - name: "Install SSL Certificate Chain to mounted ssl directory for other applications to use"
      copy:
        content: "{{ ssl_certchain }}"
        dest: "{{ data_mount_root }}/ssl/{{ www_domain }}.cert"
        owner: "{{ media_user_uid }}"
        group: "{{ media_user_gid }}"
        mode: 0640
